version: "2"
services:
    nodejs:
        build: .
        ports:
            - "8000:8000"
        tty: true
        volumes:
            - .:/usr/src/app
        env_file: .env
        working_dir: /usr/src/app
        command:
            ["/bin/sh", "-c", "yarn && yarn dev"]
networks:
    default:
        external:
            name: swarm_network
